### ISSUE TITLE
Plugin not working under Velocity

### ISSUE THREAD

**Issue by Geitenijs** [LielAmar/2FA#162]
**Describe the bug**
Plugin doesn't load under Velocity

**How To Reproduce**
1. Install plugin on Velocity proxy
2. See error

**Server Information**
 - OS: Debian 12
 - Java Version: Java 17
 - Server Game Version: Velocity 3.3.0-b413
 - Plugin Version: 1.7.1
 - Plugin List: LiteBans, PremiumVanish, Geyser, Floodgate, ViaVersion
 
**Additional context**
https://pastebin.com/mWhE0cMj

**Comment by DirtyConcept** [comment]
I have looked into the issue, and hopefully the solution I've created works properly after I run tests on it on all servers. The issue should be fixed in the branch linked to this issue.

I'll close this when the fix gets released, and hopefully it'll be soon.

Thank you very much for reporting this issue :)

**Comment by DirtyConcept** [comment]
If you'd like for it I could release on github the 1.7.2 version once I've ran the tests for you to use the plugin.

**Comment by Geitenijs** [comment]
Thanks for resolving this issue so quickly! Highly appreciate it.
