### ISSUE TITLE
Velocity Support (upcoming proxy)

### ISSUE THREAD

**Issue by Romvnly-Gaming** [LielAmar/2FA#64]
**Is your feature request related to a bug/problem? If so, please link to the relevant issue or describe it**
Velocity Support as a proxy, full support as Bungee, or even more! 

**Describe the solution you'd like**
Add proxy Velocity Support, preferably 1:1 to Bungee's feature set.

**Describe alternatives you've considered**
None, Velocity is top tier!

**Additional context**
https://velocitypowered.com

**Comment by TwinkleToes777** [comment]
I would like this as I am soon switching to Velocity. Are you sure Velocity does not support PluginMessagingChannel? Try newest version of Velocity as it may now support it.

**Comment by LielAmar** [comment]
> I would like this as I am soon switching to Velocity. Are you sure Velocity does not support PluginMessagingChannel? Try newest version of Velocity as it may now support it.

The last time I checked, Velocity did not support PluginMessagingChannel nor had any intentions to support it.
I really want to get this done with and add support to velocity, but unfortunately got absolutely no time at all to even maintain the plugin properly, not to mention add new features or support other frameworks.

If some other developer would be willing to step in and add the support to velocity, then it'd be possible. Otherwise, I can only imagine velocity support being added in around 2 months, when I finish my semester.

**Comment by OverBrave** [comment]
What is the latest status? Still no chance?

**Comment by LielAmar** [comment]
> 

I'm going to end my semester in about a month and will hopefully have enough time to implement velocity support by then :)

**Comment by kerostampcrab** [comment]
For now it is possible with [Snap!](https://forums.velocitypowered.com/t/snap-run-bungeecord-plugins-on-velocity/608).

It isn't ideal, but it seems to work fine.

Also I'm pretty sure Velocity supports Bungee's PluginMessagingChannel (but I'm no expert.)

**Comment by Romvnly-Gaming** [comment]
Most plugins on Snap! Are broken and it’s just like Mohist, a bad idea

**Comment by kerostampcrab** [comment]
It's not causing any issues so far, so I'll use it for the time being.

**Comment by Romvnly-Gaming** [comment]
Mkay

**Comment by LielAmar** [comment]
Velocity support is now added for version 1.6.0 and above :) [#77](https://github.com/LielAmar/2FA/pull/77)

**Comment by kerostampcrab** [comment]
Yees ❤️❤️
